### PR TITLE
Use vid/pid from bsp.h

### PR DESCRIPTION
**Pull request by kbeckmann**

### CODE REVIEW

**Comment by kbeckmann** [comment]
Maybe there is a better place to put the ifndef stuff, in case we want to access USB_VID from another place in the code. Suggestions?

**Comment by arturo182** [comment]
But it is already defined, just not used :) https://github.com/arturo182/tinyuf2/blob/3ba5b587f5fc2cd838fd8fb09ee71eb8bfb8db18/hw/bsp/bsp.h#L47

**Comment by kbeckmann** [comment]
Oops, thanks for the review.

**Review by arturo182 — APPROVED** [review]
Beautiful

**Pull request merged**
